language: c++
dist: bionic
addons:
  apt:
    packages:
    - zlib1g-dev
    - libreadline-dev
    - cmake
    - git
before_script:
- sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
script:
- mkdir -p build
- cd build
- LLVM_DIR=/usr/lib/llvm-10 cmake ../
- make
- ./minou-tests
