language: c++
dist: bionic
addons:
  apt:
    packages:
    - zlib1g-dev
    - libreadline-dev
    - cmake
    - git
    - llvm-8-dev
script:
- mkdir -p build
- cd build
- LLVM_DIR=/usr/lib/llvm-8 cmake ../
- make
- ./minou-tests
